apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "llm-inference.fullname" . }}
  labels:
    model-name: {{ .Values.model.name | quote }}
    model-size: {{ .Values.model.size | quote }}
    {{- include "llm-inference.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      model-name: {{ .Values.model.name | quote }}
      model-size: {{ .Values.model.size | quote }}
      {{- include "llm-inference.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        model-name: {{ .Values.model.name | quote }}
        model-size: {{ .Values.model.size | quote }}
        {{- include "llm-inference.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "llm-inference.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          ports:
            - name: http
              containerPort: 11434
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: OLLAMA_HOST
              value: "0.0.0.0"
            {{- if .Values.extraEnv }}
            {{- toYaml .Values.extraEnv | nindent 12 }}
            {{- end }}